### ISSUE TITLE
spawn npm ENOENT

### ISSUE THREAD

**Issue by yuta0801** [maxleiko/exec-npm-install#1]
Error `spawn npm ENOEN`

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

```js
var execNpmInstall = require('exec-npm-install');

execNpmInstall({
  modules: [
    'fs-extra'
  ],
  prefix: 'test/'
}, err => {
  if (err) {
    console.log('Error: '+err.message);
  } else {
    console.log('Install sucess');
  }
});
```

**Comment by maxleiko** [comment]
Are you sure `npm` is available in your context PATH?

**Comment by yuta0801** [comment]
yes

**Comment by maxleiko** [comment]
Sorry, it was a rhetorical question, the error code means that `npm` was not found when spawning the child process.

Are you on Windows?  
Which version of NodeJS do you use?  

I need more than just that error message to find out the problem :)

**Comment by maxleiko** [comment]
This https://github.com/nodejs/node-v0.x-archive/issues/5841 might be a way to solve it if you are on Windows.

**Comment by yuta0801** [comment]
That's got settled. Thanks you!
